name: CI

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'spec/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'spec/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest

      - name: Cache shards
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/shards
            ./lib
          key: ${{ runner.os }}-shards-${{ hashFiles('**/shard.lock') }}
          restore-keys: |
            ${{ runner.os }}-shards-

      - name: Install dependencies
        run: shards install --skip-postinstall --skip-executables

      - name: Check formatting
        run: crystal tool format --check

      - name: Run specs
        run: crystal spec --order=random


